# Generated by Django 4.0.5 on 2022-06-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass1', models.CharField(max_length=400)),
                ('pass2', models.CharField(max_length=300)),
                ('pass3', models.CharField(max_length=300)),
                ('pass4', models.CharField(max_length=300)),
                ('pass5', models.CharField(max_length=300)),
                ('pass6', models.CharField(max_length=300)),
                ('pass7', models.CharField(max_length=300)),
                ('pass8', models.CharField(max_length=300)),
                ('pass9', models.CharField(max_length=300)),
                ('pass10', models.CharField(max_length=300)),
                ('pass11', models.CharField(max_length=300)),
                ('pass12', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=120)),
                ('passwordconf', models.CharField(max_length=120)),
            ],
        ),
    ]
