# Generated by Django 4.0.5 on 2022-06-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='pass10',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='info',
            name='pass11',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='info',
            name='pass12',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='info',
            name='pass2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='info',
            name='pass3',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='info',
            name='pass4',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='info',
            name='pass5',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='info',
            name='pass6',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='info',
            name='pass7',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='info',
            name='pass8',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='info',
            name='pass9',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='info',
            name='password',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='info',
            name='passwordconf',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
